mvcforum/MVCForum.Website/Areas/Admin/ViewModels/BatchViewModels.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using DataAnnotationsExtensions;
using MVCForum.Domain.DomainModel;

namespace MVCForum.Website.Areas.Admin.ViewModels
{
    public class BatchDeleteMembersViewModel
    {
        [Required]
        [Numeric]
        [DisplayName("Registered in the last specified amount of days")]
        public int AmoutOfDaysSinceRegistered { get; set; }

        [Required]
        [Numeric]
        [DisplayName("And has posted less than or equal to this amount of times")]
        public int AmoutOfPosts { get; set; }

        public int AmountDeleted { get; set; }
    }

    public class BatchMoveTopicsViewModel
    {
        public List<Category> Categories { get; set; }

        [Required]        
        [DisplayName("Move all Topics in this Category")]
        public Guid? FromCategory { get; set; }

        [Required]
        [DisplayName("To this new Category")]
        public Guid? ToCategory { get; set; }
    }
}

mvcforum/MVCForum.Website/Areas/Admin/Controllers/BatchController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using MVCForum.Domain.Constants;
using MVCForum.Domain.Interfaces.Services;
using MVCForum.Domain.Interfaces.UnitOfWork;
using MVCForum.Website.Areas.Admin.ViewModels;

namespace MVCForum.Website.Areas.Admin.Controllers
{
    [Authorize(Roles = AppConstants.AdminRoleName)]
    public partial class BatchController : BaseAdminController
    {
        private readonly ICategoryService _categoryService;
        private readonly ITopicService _topicService;

        public BatchController(ILoggingService loggingService, IUnitOfWorkManager unitOfWorkManager, IMembershipService membershipService, 
            ILocalizationService localizationService, ISettingsService settingsService, ICategoryService categoryService, ITopicService topicService) 
            : base(loggingService, unitOfWorkManager, membershipService, localizationService, settingsService)
        {
            _categoryService = categoryService;
            _topicService = topicService;
        }

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult BatchDeleteMembers()
        {
            return View(new BatchDeleteMembersViewModel{AmoutOfDaysSinceRegistered = 0, AmoutOfPosts = 0});
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult BatchDeleteMembers(BatchDeleteMembersViewModel viewModel)
        {
            using (var unitOfWork = UnitOfWorkManager.NewUnitOfWork())
            {
                try
                {
                    var membersToDelete = MembershipService.GetUsersByDaysPostsPoints(viewModel.AmoutOfDaysSinceRegistered,
                                                                                        viewModel.AmoutOfPosts);
                    var count = membersToDelete.Count;
                    foreach (var membershipUser in membersToDelete)
                    {
                        MembershipService.Delete(membershipUser, unitOfWork);
                    }
                    unitOfWork.Commit();
                    TempData[AppConstants.MessageViewBagName] = new GenericMessageViewModel
                    {
                        Message = string.Format("{0} members deleted", count),
                        MessageType = GenericMessages.success
                    };
                }
                catch (Exception ex)
                {
                    unitOfWork.Rollback();
                    LoggingService.Error(ex);
                    TempData[AppConstants.MessageViewBagName] = new GenericMessageViewModel
                    {
                        Message = ex.Message,
                        MessageType = GenericMessages.danger
                    };
                }
            }

            return View();
        }

        public ActionResult BatchMoveTopics()
        {
            var viewModel = new BatchMoveTopicsViewModel
                {
                    Categories = _categoryService.GetAll().ToList()
                };
            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult BatchMoveTopics(BatchMoveTopicsViewModel viewModel)
        {
            using (var unitOfWork = UnitOfWorkManager.NewUnitOfWork())
            {
                try
                {
                    var categoryFrom = _categoryService.Get((Guid)viewModel.FromCategory);
                    var categoryTo = _categoryService.Get((Guid)viewModel.ToCategory);

                    var topicsToMove = _topicService.GetRssTopicsByCategory(int.MaxValue, categoryFrom.Id);
                    var count = topicsToMove.Count;

                    foreach (var topic in topicsToMove)
                    {
                        topic.Category = categoryTo;
                    }

                    unitOfWork.SaveChanges();

                    categoryFrom.Topics.Clear();

                    viewModel.Categories = _categoryService.GetAll().ToList();

                    unitOfWork.Commit();

                    TempData[AppConstants.MessageViewBagName] = new GenericMessageViewModel
                    {
                        Message = string.Format("{0} topics moved", count),
                        MessageType = GenericMessages.success
                    };
                }
                catch (Exception ex)
                {
                    unitOfWork.Rollback();
                    LoggingService.Error(ex);
                    TempData[AppConstants.MessageViewBagName] = new GenericMessageViewModel
                    {
                        Message = ex.Message,
                        MessageType = GenericMessages.danger
                    };
                }
            }

            return View(viewModel);
        }

    }
}

mvcforum/MVCForum.Website/Areas/Admin/Views/Batch/BatchDeleteMembers.cshtml
@model MVCForum.Website.Areas.Admin.ViewModels.BatchDeleteMembersViewModel
@{
    ViewBag.Title = "Batch Delete Members";
}

<h2>Batch Delete Members</h2>

<p>
    Batch delete members that have registered within a set amount of days and have less than or equal to the specified post count.
    i.e. To delete members who haven't posted, within the last year then you would set the following.
</p>
<p>
    <strong>Amount Of Days = 365</strong>
    <br />
    <strong>Amount Of Posts = 0</strong>
</p>
<p>As soon as you click the button members will be deleted. This action cannot be undone.</p>


@using (Html.BeginForm("BatchDeleteMembers", "Batch", FormMethod.Post))
{
    @Html.ValidationSummary(false)
    @Html.AntiForgeryToken()

    <div class="form-group">
        @Html.LabelFor(m => m.AmoutOfDaysSinceRegistered)
        @Html.TextBoxFor(m => m.AmoutOfDaysSinceRegistered, new { @class = "form-control", type="number" })
        @Html.ValidationMessageFor(m => m.AmoutOfDaysSinceRegistered)
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.AmoutOfPosts)
        @Html.TextBoxFor(m => m.AmoutOfPosts, new { @class = "form-control", type = "number" })
        @Html.ValidationMessageFor(m => m.AmoutOfPosts)
    </div>

    <div class="submit-holder">
        <input type="submit" class="btn-mvc btn-mvc-green" value="Delete Members" />
    </div>


}

mvcforum/MVCForum.Website/Areas/Admin/Views/Batch/BatchMoveTopics.cshtml
@model MVCForum.Website.Areas.Admin.ViewModels.BatchMoveTopicsViewModel

@{
    ViewBag.Title = "Batch Move Topics";
}

<h2>Batch Move Topics</h2>
<p>Use this tool to move all topics from one category to another one.</p>
<p>As soon as you click the button the topics will be moved.</p>


@using (Html.BeginForm("BatchMoveTopics", "Batch", FormMethod.Post))
{
    @Html.ValidationSummary(false)
    @Html.AntiForgeryToken()

    <div class="row">
        <div class="col-md-6">
            <div class="form-group">
                @Html.LabelFor(m => m.FromCategory)
                @Html.DropDownListFor(m => m.FromCategory, new SelectList(Model.Categories, "Id", "Name"), new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.FromCategory)
            </div>
        </div>
        <div class="col-md-6">
            <div class="form-group">
                @Html.LabelFor(m => m.ToCategory)
                @Html.DropDownListFor(m => m.ToCategory, new SelectList(Model.Categories, "Id", "Name"), new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.ToCategory)
            </div>
        </div>
    </div>

    <div class="submit-holder">
        <input type="submit" class="btn-mvc btn-mvc-green" value="Move Topics" />
    </div>

}

mvcforum/MVCForum.Website/Areas/Admin/Views/Batch/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Batch Tools</h2>
<p>This section will allow you to perform batch tasks</p>

<div class="panel panel-default">
    <div class="panel-body">
        <h3>Batch Delete Members</h3>
        <p>This tool will allow you to batch delete members that haven't posted and registed within a set amount of days</p>
        <a href="@Url.Action("BatchDeleteMembers", "Batch", new { area = "Admin" }, null)" class="btn-mvc btn-mvc-green">Go to Batch Delete Members</a>

    </div>
</div>


<div class="panel panel-default">
    <div class="panel-body">
        <h3>Batch Move Topics</h3>
        <p>This tool allows you to batch move topics into another category</p>
        <a href="@Url.Action("BatchMoveTopics", "Batch", new { area = "Admin" }, null)" class="btn-mvc btn-mvc-green">Go to Batch Move Topics</a>

    </div>
</div>